name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1             # Your AWS region
  EB_ENV_NAME: Node-cicd-demo-env    # Your Elastic Beanstalk Environment name

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Elastic Beanstalk CLI
      run: |
        pip install awsebcli --upgrade --user
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Deploy to Elastic Beanstalk
      run: |
        # Deploy to existing environment
        eb deploy ${{ env.EB_ENV_NAME }}
